# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xATb0B0XkQp_quvjkhsfWUC0WeCUQVE
"""

# mystr = '''无码
# 啊	a	aaka
# 阿	aa
# 啊啊啊	aaa
# 阿爸	aaba
# 嗷嗷待哺	aadb
# 阿斗	aadb
# 暗暗称奇	aaiq
# 锕	aaj
# 安安静静	aajj
# 阿姐	aajx
# 吖	aak
# 吁	aaky
# 阿拉	aala
# 腌	aao
# 安安心心	aaxx
# 的	d	debu
# 打	da
# 大	daa
# 大碍	daai
# 答案	daan
# 瘩	dab
# 大把	daba
# 打靶	daba
# 达标	dabc
# 疸	dabd
# 一	y yyy
# 刀  dkp
# 到  dk
# 对立统一规律	dltl
# 没	m	mzdu
# 没工夫'''

# lines = mystr.splitlines()


韵母转换映射表 = {
    # 自然码 : 小鹤
    "z": "w",
    "p": "y",
    "x": "p",
    "l": "d",
    "y": "k",
    "d": "l",
    "b": "z",
    "w": "x",
    "k": "c",
    "n": "b",
    "c": "n",
}


def 韵母转换(原韵母):
    if 原韵母 in 韵母转换映射表:
        return 韵母转换映射表[原韵母]
    else:
        return 原韵母


码表 = []

with open("moran_fixed_simp.dict.txt", "r", encoding="utf-8") as lines:
    for line in lines:

        if line == "\n":
            continue

        [字, *码] = line.strip().split()
        if not 码:
            # print(字)
            码表.append(字)

        else:

            if len(字) >= 3:
                # print(f'{字}\t{码[0]}')
                码表.append(f"{字}\t{码[0]}")

            if len(字) == 2:
                if len(码[0]) ==2:
                    码表.append(f"{字}\t{码[0]}")

                if len(码[0]) ==4:
                    声1 = 码[0][0]
                    韵1 = 码[0][1]
                    声2 = 码[0][2]
                    韵2 = 码[0][3]

                    韵1 = 韵母转换(韵1)
                    韵2 = 韵母转换(韵2)

                    # print(f'{字}\t{声1}{韵1}{声2}{韵2}')
                    码表.append(f"{字}\t{声1}{韵1}{声2}{韵2}")


            if len(字) == 1:
                if len(码) > 1:  # 码[0] 简码 \t 码[1] 全码

                    简码 = 码[0]

                    声 = 码[1][0]
                    韵 = 韵母转换(码[1][1])
                    辅助码 = 码[1][2:]

                    # print(f'{字}\t{简码}\t{声}{韵}{辅助码}')
                    码表.append(f"{字}\t{简码}\t{声}{韵}{辅助码}")

                if len(码) == 1:
                    # 打	da
                    # 大	daa
                    声 = 码[0][0]
                    韵 = 韵母转换(码[0][1])
                    辅助码 = 码[0][2:]

                    # print(f'{字}\t{声}{韵}{辅助码}')
                    码表.append(f"{字}\t{声}{韵}{辅助码}")

# for line in 码表:
#    print(line)

with open("myfile1.txt", "w", encoding="utf-8") as f:
    for line in 码表:
        f.write(f"{line}\n")

